// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_gwxbWZLvSWpOYxZTQyuxvtWF3aekXc',
    appId: '1:243743366735:web:ce2859a7026d69e6b1943a',
    messagingSenderId: '243743366735',
    projectId: 'airplane-7ee65',
    authDomain: 'airplane-7ee65.firebaseapp.com',
    storageBucket: 'airplane-7ee65.firebasestorage.app',
    measurementId: 'G-91F4TJXK9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN63ISxjh6yghPHOUE2xAGwsFpPBxJ4-M',
    appId: '1:243743366735:android:e61e6d16768e5ac4b1943a',
    messagingSenderId: '243743366735',
    projectId: 'airplane-7ee65',
    storageBucket: 'airplane-7ee65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1sP5viEkiWyJo1lhGWAoRKVqkU5wd-Y',
    appId: '1:243743366735:ios:93e7115e936baefeb1943a',
    messagingSenderId: '243743366735',
    projectId: 'airplane-7ee65',
    storageBucket: 'airplane-7ee65.firebasestorage.app',
    iosBundleId: 'com.example.appAirplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1sP5viEkiWyJo1lhGWAoRKVqkU5wd-Y',
    appId: '1:243743366735:ios:93e7115e936baefeb1943a',
    messagingSenderId: '243743366735',
    projectId: 'airplane-7ee65',
    storageBucket: 'airplane-7ee65.firebasestorage.app',
    iosBundleId: 'com.example.appAirplane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_gwxbWZLvSWpOYxZTQyuxvtWF3aekXc',
    appId: '1:243743366735:web:9ef9ecc9d4cccd5eb1943a',
    messagingSenderId: '243743366735',
    projectId: 'airplane-7ee65',
    authDomain: 'airplane-7ee65.firebaseapp.com',
    storageBucket: 'airplane-7ee65.firebasestorage.app',
    measurementId: 'G-1QE14FK9QW',
  );
}
